create unique index uk_cifm_flow_status on CIFM_FLOW_STATUS(id);
create unique index uk_CIFM_PERSON_INFO on CIFM_PERSON_INFO(id);
create index idx_CIFM_PERSON_INFO1 on CIFM_PERSON_INFO(client_name);
create index idx_CIFM_PERSON_INFO2 on CIFM_PERSON_INFO(CREDENTIALS_NO);
create index idx_CIFM_PERSON_detail1 on CIFM_PERSON_detail(client_name);
create index idx_CIFM_PERSON_detail2 on CIFM_PERSON_detail(CREDENTIALS_NO);
create index idx_CIFM_company_INFO1 on CIFM_company_INFO(COMPANY_NAME);
create index idx_CIFM_company_INFO2 on CIFM_company_INFO(CHINA_CREDIT_CODE);
create index idx_CIFM_company_detail1 on CIFM_company_detail(COMPANY_NAME);
create index idx_CIFM_company_detail2 on CIFM_company_detail(CHINA_CREDIT_CODE);
create unique index uk_cifm_flow_status_his on cifm_flow_status_his(id);
create unique index uk_CIFM_PERSON_INFO_his on CIFM_PERSON_INFO_his(id);
create index idx_CIFM_PERSON_INFO_his1 on CIFM_PERSON_INFO_his(client_name);
create index idx_CIFM_PERSON_INFO_his2 on CIFM_PERSON_INFO_his(CREDENTIALS_NO);
create index idx_CIFM_PERSON_detail_his1 on CIFM_PERSON_detail_his(client_name);
create index idx_CIFM_PERSON_detail_his2 on CIFM_PERSON_detail_his(CREDENTIALS_NO);
create index idx_CIFM_company_INFO_his1 on CIFM_company_INFO_his(COMPANY_NAME);
create index idx_CIFM_company_INFO_his2 on CIFM_company_INFO_his(CHINA_CREDIT_CODE);
create index idx_CIFM_company_detail_his1 on CIFM_company_detail_his(COMPANY_NAME);
create index idx_CIFM_company_detail_his2 on CIFM_company_detail_his(CHINA_CREDIT_CODE);