
package com.dcits.credit.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceAcceptWSQuery", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IServiceAcceptWSQuery {


    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String psCreditReportQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String statusQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String statusVariableQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String uploadQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String statusScoreQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

    /**
     * 
     * @param querymessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String bsCreditReportQueryReq(
        @WebParam(name = "querymessage", partName = "querymessage")
        String querymessage);

}
