
package com.dcits.credit.wsimport;

import java.net.MalformedURLException;
import java.net.URL;

import javax.annotation.Resource;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.dcits.platform.dao.DaoSupport;
import com.dcits.platform.util.PageData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceAcceptWSQuery", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", wsdlLocation = "http://172.200.100.57:8080/creditreference/v2/prod/channel-query/ServiceAccept?wsdl")
public class IServiceAcceptWSQuery_Service
    extends Service
{

    private final static URL ISERVICEACCEPTWSQUERY_WSDL_LOCATION;
    private final static WebServiceException ISERVICEACCEPTWSQUERY_EXCEPTION;
    private final static QName ISERVICEACCEPTWSQUERY_QNAME = new QName("http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", "IServiceAcceptWSQuery");
    @Resource(name = "daoSupport")
	private static DaoSupport dao;
    
    static {
        URL url = null;
        WebServiceException e = null;
        try {
//        	PageData pd = new PageData();
//        	String sql = "SELECT VALUE from SERVER_MESSAGE_INFO  WHERE CODE = 'PER_Url'";
//        	pd.put("selectSql", sql);
//        	PageData str = (PageData) dao.findForObject("IndAppReMapper.selectPdInfo", pd);
            //url = new URL("http://9.88.47.3/creditreference/v2/prod/channel-query/ServiceAccept?wsdl");
//        	url = new URL("http://172.200.100.57:80/creditreferencetest/v2/test/channel-query/ServiceAccept?wsdl");
        	url = new URL("http://172.200.100.57:8080/creditreference/v2/prod/channel-query/ServiceAccept?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        ISERVICEACCEPTWSQUERY_WSDL_LOCATION = url;
        ISERVICEACCEPTWSQUERY_EXCEPTION = e;
    }

    public IServiceAcceptWSQuery_Service() {
        super(__getWsdlLocation(), ISERVICEACCEPTWSQUERY_QNAME);
    }

    public IServiceAcceptWSQuery_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEACCEPTWSQUERY_QNAME, features);
    }

    public IServiceAcceptWSQuery_Service(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEACCEPTWSQUERY_QNAME);
    }

    public IServiceAcceptWSQuery_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEACCEPTWSQUERY_QNAME, features);
    }

    public IServiceAcceptWSQuery_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceAcceptWSQuery_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceAcceptWSQuery
     */
    @WebEndpoint(name = "ServiceAcceptWSQueryImplPort")
    public IServiceAcceptWSQuery getServiceAcceptWSQueryImplPort() {
        return super.getPort(new QName("http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", "ServiceAcceptWSQueryImplPort"), IServiceAcceptWSQuery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceAcceptWSQuery
     */
    @WebEndpoint(name = "ServiceAcceptWSQueryImplPort")
    public IServiceAcceptWSQuery getServiceAcceptWSQueryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", "ServiceAcceptWSQueryImplPort"), IServiceAcceptWSQuery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEACCEPTWSQUERY_EXCEPTION!= null) {
            throw ISERVICEACCEPTWSQUERY_EXCEPTION;
        }
        return ISERVICEACCEPTWSQUERY_WSDL_LOCATION;
    }

}
