CREATE USER SENSE
  IDENTIFIED BY SENSE
  DEFAULT TABLESPACE TS_SENSE_DATA
  TEMPORARY TABLESPACE TS_SENSE_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SENSE
  GRANT CONNECT TO SENSE;
  GRANT RESOURCE TO SENSE;
  ALTER USER SENSE DEFAULT ROLE ALL;
  -- 5 System Privileges for SENSE
  GRANT CREATE ANY VIEW TO SENSE;
  GRANT DROP ANY VIEW TO SENSE;
  GRANT UNLIMITED TABLESPACE TO SENSE;
  GRANT DEBUG ANY PROCEDURE TO SENSE;
  GRANT SELECT ANY TABLE TO SENSE;
  GRANT DEBUG CONNECT SESSION TO SENSE;

/
exit
