CREATE TABLESPACE TS_SENSE_DATA DATAFILE  'c:\TS_SENSE_DATA01.dbf' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 5000M;
CREATE TEMPORARY TABLESPACE TS_SENSE_TMP TEMPFILE  'c:\TS_SENSE_TEMP01.dbf' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 5000M;
exit;
