update COM_ACTUAL_CONTROLLER set NAME_IDENTITY = encrypt_des(NAME_IDENTITY),TYPE_IDENTITY = encrypt_des(TYPE_IDENTITY),TYPE_IDENTITY_NUM = encrypt_des(TYPE_IDENTITY_NUM);

update COM_CREDIT_BASIC_INFO set ADDRESS_EDI = encrypt_des(ADDRESS_EDI),ADDRE_BUSS = encrypt_des(ADDRE_BUSS),LICENSE_DATE = encrypt_des(LICENSE_DATE);


update COM_DIRECT_CONN_OTHERS set CHINA_CREDIT_CODE = encrypt_des(CHINA_CREDIT_CODE),COM_NAME = encrypt_des(COM_NAME);

update COM_IDENT_BASIC set NUM_ENT_INDENT = encrypt_des(NUM_ENT_INDENT),TYPE_ENT_IDENT = encrypt_des(TYPE_ENT_IDENT);

update COM_INVESTOR_INFO set INVE_CRED_NUM = encrypt_des(INVE_CRED_NUM),INVE_CRED_TYPE = encrypt_des(INVE_CRED_TYPE),INVE_NAME = encrypt_des(INVE_NAME),INVE_PERCENT = encrypt_des(INVE_PERCENT);

update COM_REPORT_INFO set ENT_NAME = encrypt_des(ENT_NAME),ORG_CODE = encrypt_des(ORG_CODE),QUERY_REASON = encrypt_des(QUERY_REASON),REPORT_TIME = encrypt_des(REPORT_TIME);

update COM_SENIOR_MANAGER_INFO set SENIOR_DUTIES = encrypt_des(SENIOR_DUTIES),SENIOR_NAME = encrypt_des(SENIOR_NAME),SNEIOR_CRED_NUM = encrypt_des(SNEIOR_CRED_NUM),SNEIOR_CRED_TYPE = encrypt_des(SNEIOR_CRED_TYPE);

update PER_BASIC set CLIENT_BIRTHDAY = encrypt_des(CLIENT_BIRTHDAY),CLIENT_NAME = encrypt_des(CLIENT_NAME),COMPANY_TEL = encrypt_des(COMPANY_TEL),CREDENTIALS_NO = encrypt_des(CREDENTIALS_NO),DIGITAL_INTERPRE = encrypt_des(DIGITAL_INTERPRE),DIGITAL_INTERPRE_DES_CNT = encrypt_des(DIGITAL_INTERPRE_DES_CNT),FAMILY_TEL = encrypt_des(FAMILY_TEL),MAILING_ADDRESS = encrypt_des(MAILING_ADDRESS),PHONE_NUM = encrypt_des(PHONE_NUM),RELATIVE_POSITIONT = encrypt_des(RELATIVE_POSITIONT),RESIDENCE_ADDRESS = encrypt_des(RESIDENCE_ADDRESS);

update PER_CAREER set COMPANY_ADDRESS = encrypt_des(COMPANY_ADDRESS),COMPANY_NAME = encrypt_des(COMPANY_NAME),COMPANY_TEL = encrypt_des(COMPANY_TEL),JOB_TITLE = encrypt_des(JOB_TITLE);

update PER_LIVE set FAMILY_TEL = encrypt_des(FAMILY_TEL),HOUSE_TEL = encrypt_des(HOUSE_TEL),RESIDENTIAL_ADDRESS = encrypt_des(RESIDENTIAL_ADDRESS);

update PER_LOW_SECURITY set COMPANY = encrypt_des(COMPANY);
update PER_OTHER_IDENTITY set CREDENTIALS_NO = encrypt_des(CREDENTIALS_NO);
update PER_PENSIO_PAY set PAY_COM_NAME = encrypt_des(PAY_COM_NAME);
update PER_PENSIO_RELEASE set ORIGINAL_COMAPNY = encrypt_des(ORIGINAL_COMAPNY);
update PER_PHONE_INFO set PHONE_NUM = encrypt_des(PHONE_NUM);
update PER_PROVIDENT_FUND_PAY set PAY_COM_NAME = encrypt_des(PAY_COM_NAME);
update PER_SPOU set SPOU_COMPANY = encrypt_des(SPOU_COMPANY),SPOU_CREDENTIALS_NO = encrypt_des(SPOU_CREDENTIALS_NO),SPOU_NAME = encrypt_des(SPOU_NAME),SPOU_TEL = encrypt_des(SPOU_TEL);

update PER_VEHICLE_TRANSACTION set ENGINE_NUM = encrypt_des(ENGINE_NUM),PLATE_NUM = encrypt_des(PLATE_NUM);
