
update sys_dict set dic_code='register_type1'  where dic_idvalue='2d977b51870243c488fa246dff96cab1'

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('Entywzl', '企业业务种类（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '1779285f11f543c0838c7e5a8d26df54', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('IMPORT_STATUS', '重要信息提示状态', null, 'SYS_DICTIONARIES', 'PARENT_ID', '916495768951460aa05509784c559616', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('EntIDType', '企业身份标识类型（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', 'ac581082cd634495bda73f2b9dddac66', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('EntFindReason', '查询原因（二代企业）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '4c610bed73ba4611b424c1f409895d67', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('ywzl', '个人业务种类（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '04bf670abd6b4da1848e297650869245', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('infoCategroy', '个人定位信息类别（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '192451f160a14bb593c2f473d931abff', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('CRED_TYPE_COM', '证件类型（二代企业）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '627b5cae18554575a765fe176179680f', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('handInfo', '处理信息（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', 'e143d945c4144ee1a31128d2206f39c7', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('numReadQueryReason', '查询原因（数字解读）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '1779a6cd2670495bbdbc710d1734445f', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('checkResult', '核查结果（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', 'a8bae89b15fb43bf8dce1f42c619fb27', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('CRED_TYPE_PER', '证件类型（二代个人）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '4ded56a895f142339fab546cfb9aab18', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('infoCode', '信息代码（数字解读）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '510841cc465043e1ac73d006787c3276', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('resultType', '查询结果类型（数字解读）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '4d334633514445f38ab31d89ba647a2c', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('EntinfoCategroy', '企业定位信息类别（异议处理）', null, 'SYS_DICTIONARIES', 'PARENT_ID', 'ed8bb890fa5747718a86db4602245644', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('find_reason_per', '查询原因（二代个人）', null, 'SYS_DICTIONARIES', 'PARENT_ID', '8fb9d3316d2940218a9e54b76b829114', 'DICT_CODE', 'NAME', null, null, null);

insert into SYS_DICT (dic_code, dic_des, dic_type, dic_tblname, dic_id_colname, dic_idvalue, dic_val_colname, dic_des_colname, remark, dic_sort_colname, dic_dynamic_sign)
values ('creditType', '账号类型', null, 'SYS_DICTIONARIES', 'PARENT_ID', 'bf5eb052cd4343708058e312d4970ba3', 'DICT_CODE', 'NAME', null, null, null);

insert into sys_dict (DIC_CODE, DIC_DES, DIC_TYPE, DIC_TBLNAME, DIC_ID_COLNAME, DIC_IDVALUE, DIC_VAL_COLNAME, DIC_DES_COLNAME, REMARK, DIC_SORT_COLNAME, DIC_DYNAMIC_SIGN)
values ('register_type', '登记注册类型', null, 'SYS_DICTIONARIES', 'PARENT_ID', '46c5d2d0ecd9422ab3eec2f477f27b21', 'DICT_CODE', 'NAME', null, null, null);

commit;

